[package]
name = "rs"
version = "0.1.0"
authors = ["lauri <lauri.nomme@gmail.com>"]
edition = "2018"

[dependencies]
tower-web = "0.3.7"
serde = { version = "1.0", features = ["derive"] }
tokio = "0.1.21"
clap = { version = "2.33", default-features = false, features = [ "suggestions"] }

